apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress
secretGenerator:
- name: mysql-pass
  literals:
  - password=qwerty11223344
resources:
  - src-local.yaml
  - pv-local.yaml
  - wordpress-deployment.yaml
  - mysql-deployment.yaml
